

GET http://localhost:8000/todos

###

GET http://localhost:8000/todos/617fa07c892d5c34cc8be11f

###

POST http://localhost:8000/todos Content-Type: application/json

{
    "name":"roni the man", "age":165, "complete": true

}

###
DELETE http://localhost:8000/todos/617fa07c892d5c34cc8be11f ###

###
PATCH http://localhost:8000/todos/617fa07c892d5c34cc8be11f Content-Type: application/json

{
    "name":"momomomo", "age":324432, "complete": true

}








